FROM ubuntu:24.04
LABEL Description="C++ Development environment"

SHELL ["/bin/bash", "-c"]

RUN apt-get update && apt-get -y --no-install-recommends install \
    wget \
    sudo \
    clang \
    clangd \
    clang-format \
    clang-tools \
    cmake \
    make \
    ninja-build \
    pipx \
    neovim \
    tmux \
    tldr \
    bat \
    curl \
    gdb \
    less

RUN LAZYGIT_VERSION=$(curl -s "https://api.github.com/repos/jesseduffield/lazygit/releases/latest" | grep -Po '"tag_name": "v\K[^"]*') && \
    curl -Lo lazygit.tar.gz "https://github.com/jesseduffield/lazygit/releases/latest/download/lazygit_${LAZYGIT_VERSION}_Linux_x86_64.tar.gz" && \
    tar xf lazygit.tar.gz lazygit && \
    sudo install lazygit /usr/local/bin && \
    rm -rf lazygit.tar.gz lazygit

COPY --chown=ubuntu:ubuntu bashrc /home/ubuntu/.bashrc
COPY --chown=ubuntu:ubuntu bash_aliases /home/ubuntu/.bash_aliases
COPY --chown=ubuntu:ubuntu tmux.conf /home/ubuntu/.config/tmux/
COPY --chown=ubuntu:ubuntu conan_profile /home/ubuntu/.conan2/profiles/default

RUN usermod -G sudo,root ubuntu
RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
USER ubuntu
WORKDIR /home/ubuntu

RUN pipx install conan && \
    tldr --update

RUN git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf && \
    ~/.fzf/install

RUN mkdir -p ~/.config/tmux/plugins && \
    git clone https://github.com/tmux-plugins/tpm ~/.config/tmux/plugins/tpm && \
    ~/.config/tmux/plugins/tpm/scripts/install_plugins.sh

