FROM ubuntu:24.04
LABEL Description="C++ Development environment"

SHELL ["/bin/bash", "-c"]

RUN apt-get update && apt-get -y --no-install-recommends install \
    wget \
    sudo \
    clang \
    clangd \
    clang-format \
    cmake \
    ninja-build \
    pipx \
    neovim \
    tmux \
    tldr \
    bat

RUN usermod -G sudo,root ubuntu
RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
USER ubuntu
WORKDIR /home/ubuntu

COPY bashrc /home/ubuntu/.bashrc

RUN pipx install conan && \
    tldr --update
